### ISSUE TITLE
History.md missing

### ISSUE THREAD

**Issue by pierre-imerir** [yoann-imerir/soc-3a-amiel-catala#1]
Please provide the requested History.md file with daily updates

**Comment by Dragaeran** [comment]
Fixed.

**Comment by pierre-imerir** [comment]
Fixed => Only if committed & pushed ;-)
Not fixed yet.
You may mark this as closed once History.md is actually visible on your public repository

**Comment by Dragaeran** [comment]
Erf, of course, I forgot again that I was dumb.
